fetch('./example/can.json')
.then(response => response.json())
.then(data => console.log(data))
.then(() => fetch('./example/osman.json'))
.then(response => response.json())
.then(data => console.log(data))
.then(() => fetch('./example/tuba.json'))
.then(response => response.json())
.then(data => console.log(data))
.catch(error => console.log(error))